from os import listdir
from os.path import isfile, join, dirname, abspath

if not __name__ == "__main__":
    exit(1)

baseDir = abspath(join(dirname(__file__), '..'))

OutputDir = join(baseDir, 'graphx')
baseSvgDir = join(baseDir, 'graphx', 'svg')

mainSvgFNames = [f for f in listdir(baseSvgDir) if isfile(join(baseSvgDir, f)) and f.lower().endswith('.svg')]

mainSvgFNames.sort()

mainSvgFiles = {}

init_str =  "# Graphics package\n"
init_str += "# This file is auto-generated by svg2pyfiles.py\n"
init_str += "# Do not edit this file directly!\n\n"

for svgFile in mainSvgFNames:
    svgFilePath = join(baseSvgDir, svgFile)
    with open(svgFilePath, 'r') as f:
        mainSvgFiles[svgFile] = f.read()

mainOutputPath = join(OutputDir, 'MainSvgFiles.py')

with open(mainOutputPath, 'w', encoding='utf-8', newline='\n') as f:
    f.write("# This file is auto-generated by svg2pyfiles.py\n")
    f.write("# Do not edit this file directly!\n\n")
    f.write("mainSvgFiles = {\n")
    for fname, content in mainSvgFiles.items():
        f.write(f'    "{fname}": b"""{content}""",\n')
    f.write("}\n")
init_str += "from .MainSvgFiles import mainSvgFiles\n"

init_str += '\n__all__ = ["mainSvgFiles"]\n'
with open(join(OutputDir, "__init__.py"), 'w', encoding='utf-8', newline='\n') as f:
    f.write(init_str)
